#!/bin/bash

path=$1
file=${path##*/}
label=${file%_*}
dir=${path%/*}

admin_keypass="${dir}/keypass"
if [ -f "$admin_keypass" ]; then
  passphrase=$($admin_keypass)
  echo -n $passphrase
fi

keybox_keypass="${dir}/${label}_keypass"
if [ -f "$keybox_keypass" ]; then
  passphrase=$($keybox_keypass)
  echo -n $passphrase
fi