apiVersion: "operator.nevis-security.ch/v1"
kind: "NevisKeyStore"
metadata:
  name: "auth-sh4r3d-default-default-signer"
  namespace: "component"
  labels:
    deploymentTarget: "auth"
spec:
  cn: "auth"
  usage: "<reserved for future use>"
  san:
    dns:
    - "auth"
    - "auth.component"
    email: []
